# docker-compose.yml

version: '3.8'

services:
  dm_web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    container_name: DM_web
    restart: always
    tty: true
    environment:
      - DATABASE_URL=mysql://root:12345@DM_mysql:3307/duel_masters
    depends_on:
      - dm_db
  dm_db:
    image: mysql:8.0
    volumes:
      - ./mysql/dbdata/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    container_name: DM_mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=duel_masters
      - MYSQL_ROOT_PASSWORD=12345
