# docker-compose.yml

version: '3.8'

services:
  dm_db:
    image: mysql:8.0
    volumes:
      - ./mysql/dbdata/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    container_name: dm_db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=duel_masters
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_WAIT_TIMEOUT=31536000
      - MYSQL_INTERACTIVE_TIMEOUT=31536000
    
  dm_api:
    build: .
    command: sh -c "while ! nc -z dm_db 3306; do sleep 1; done && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    container_name: dm_api
    restart: always
    tty: true
    environment:
      - DATABASE_URL=mysql://root:12345@dm_db:3306/duel_masters
    depends_on:
      - dm_db


  dm_web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    container_name: dm_web
    restart: always
    tty: true
    stdin_open: true
    volumes:
       - ./web:/usr/src/app/dm_web
       - /usr/src/app/dm_web/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - dm_api
